apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 'cellr-backend-app-${ parameters.purpose }'
  namespace: '${ parameters.namespace }'
  labels:
    purpose: '${ parameters.purpose }'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cellr-backend-app
      purpose: '${ parameters.purpose }'
  template:
    metadata:
      labels:
        app: cellr-backend-app
        purpose: '${ parameters.purpose }'
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: cellr-backend
        image: harbor.pb2.gcp.paasify.org/library/cellr-backend
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 8080