apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cellr-backend-ingress
  namespace: '${ parameters.namespace }'
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: clouddns
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - '${ parameters.ingress }'
    secretName: cellr-backend-tls
  rules:
  - host: '${ parameters.ingress }'
    http:
      paths:
      - backend:
          serviceName: cellr-backend
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cellr-backend
  namespace: '${ parameters.namespace }'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cellr-backend
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cellr-backend
  namespace: '${ parameters.namespace }'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cellr-backend
  template:
    metadata:
      labels:
        app: cellr-backend
    spec:
      containers:
      - name: cellr-backend
        image: harbor.pb2.gcp.paasify.org/library/cellr-backend
        ports:
        - containerPort: 8080