apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cellr-backend-app
  namespace: '${ parameters.namespace }'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cellr-backend-app
  template:
    metadata:
      labels:
        app: cellr-backend-app
    spec:
      containers:
      - name: cellr-backend
        image: harbor.pb2.gcp.paasify.org/library/cellr-backend
        ports:
        - containerPort: 8080