resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 5m
  source:
    repository: nthomson-pivotal/cellr-backend
    access_token: ((github-access-token))

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: unit-tests
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 11.0}
      inputs:
        - name: pull-request
      run:
        dir: "pull-request"
        path: "./mvnw"
        args: ["test"]

    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
  - put: pull-request
    params:
      path: pull-request
      status: success